---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: awscogs
  name: awscogs
spec:
  selector:
    app: awscogs
  type: ClusterIP
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
