---
deployment:
  replicas: 1
  image: jjeffers/awscogs:v0.1.0
  resources: {}
  env: {}

ingress:
  enable: false
  host: awscogs.example.com

serviceAccount:
  create: true
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::123456789012:role/awscogs
